console.log(a+b);
console.log("hi....");

//it  contains error , so we put this code into a try catch block